# Generated by Django 4.2.7 on 2024-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_books_app', '0010_remove_chatroom_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_image',
            field=models.ImageField(default='default_room_image.jpeg', upload_to='room_images/'),
        ),
    ]
