# Generated by Django 4.2.7 on 2024-06-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_books_app', '0013_alter_book_cover_image_alter_chatroom_room_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='/images/default_book_cover_image.png', upload_to='book_covers/'),
        ),
    ]
