# Generated by Django 4.2.7 on 2024-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_books_app', '0014_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='images/default_book_cover_image.png', upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_image',
            field=models.ImageField(default='images/default_room_image.png', upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default_user_profile_image.png', upload_to='profile_images/'),
        ),
    ]
