# Generated by Django 4.2.7 on 2024-06-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_books_app', '0015_alter_book_cover_image_alter_chatroom_room_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_by',
            new_name='owner',
        ),
    ]
